// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhpgtcrhsdbzzkgecrau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocGd0Y3Joc2RienprZ2VjcmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTc4NjgsImV4cCI6MjA1ODU3Mzg2OH0.DAN4xK9liCwy0h8kYcB-YL7Yk7MBcY1qv_OOCOkdMNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);